const { Quote } = require('../models')

const quoteData = [
  { author: "Jean-Paul Sartre", quote: "If you're lonely when you're alone, you're in bad company." },
  { author: "Jean-Paul Sartre", quote: "Do you think that I count the days? There is only one day left, always starting over: it is given to us at dawn and taken away from us at dusk." },
  { author: "Jean-Paul Sartre", quote: "Man is condemned to be free; because once thrown into the world, he is responsible for everything he does. It is up to you to give life a meaning." },
  { author: "Jean-Paul Sartre", quote: "We are our choices." },
  { author: "Jean-Paul Sartre", quote: "You are -- your life, and nothing else." },
  { author: "Jean-Paul Sartre", quote: "Smooth and smiling faces everywhere, but ruin in their eyes." },
  { author: "Simone De Beauvoir", quote: "If you live long enough, you'll see that every victory turns into a defeat." },
  { author: "Simone De Beauvoir", quote: "Change your life today.Don't gamble on the future, act now, without delay." },
  { author: "Simone De Beauvoir", quote: "I could see no reason for being sad.It´s just that it makes me unhappy not to feel happy." },
  { author: "Simone De Beauvoir", quote: "Self - consciousness is not knowledge but a story one tells about oneself." },
  { author: "Simone De Beauvoir", quote: "I love you, with a touch of tragedy and quite madly." },
  { author: "Simone De Beauvoir", quote: "All success cloaks a surrender." },
  { author: "Simone De Beauvoir", quote: "The whole world was nothing but an exile with no hope of a return." },
  { author: "Albert Camus", quote: "The only serious question in life is whether to kill yourself or not." },
  { author: "Albert Camus", quote: "We don't have the time to completely be ourselves. We only have the room to be happy." },
  { author: "Albert Camus", quote: "Mother died today.Or maybe yesterday, I don't know." },
  { author: "Albert Camus", quote: "It would take patience to wait for the Last Judgement.But that's it, we're in a hurry." },
  { author: "Albert Camus", quote: "The misery and greatness of this world: it offers no truths, but only objects for love.Absurdity is king, but love saves us from it." },
  { author: "Albert Camus", quote: "Freedom is nothing but a chance to be better." },
  { author: "Albert Camus", quote: "He who despairs of the human condition is a coward, but he who has hope for it is a fool." },
  { author: "Albert Camus", quote: "There is no love of life without despair of life." },
  { author: "Albert Camus", quote: "To be happy we must not be too concerned with others." },
  { author: "Albert Camus", quote: "You will never be happy if you continue to search for what happiness consists of.You will never live if you are looking for the meaning of life." },
  { author: "Albert Camus", quote: "Truth, like light, blinds.Falsehood, on the contrary, is a beautiful twilight that enhances every object." },
  { author: "Albert Camus", quote: "We continue to shape our personality all our life.If we knew ourselves perfectly, we should die." },
  { author: "Albert Camus", quote: "The absurd is the essential concept and the first truth." },
  { author: "Albert Camus", quote: "There is no fate that cannot be surmounted by scorn." },
  { author: "Friedrich Nietzsche", quote: "To live is to suffer, to survive is to find some meaning in the suffering." },
  { author: "Friedrich Nietzsche", quote: "That which does not kill us makes us stronger." },
  { author: "Friedrich Nietzsche", quote: "One must still have chaos in oneself to be able to give birth to a dancing star." },
  { author: "Friedrich Nietzsche", quote: "You have your way. I have my way. As for the right way, the correct way, and the only way, it does not exist." },
  { author: "Friedrich Nietzsche", quote: "The most common lie is that which one lies to himself; lying to others is relatively an exception." },
  { author: "Friedrich Nietzsche", quote: "The demand to be loved is the greatest of all arrogant presumptions." },
  { author: "Friedrich Nietzsche", quote: "A pair of powerful spectacles has sometimes sufficed to cure a person in love." },
  { author: "Friedrich Nietzsche", quote: "Success has always been a great liar." },
  { author: "Friedrich Nietzsche", quote: "To forget one's purpose is the commonest form of stupidity." },
  { author: "Friedrich Nietzsche", quote: "Convictions are more dangerous foes of truth than lies." },
  { author: "Friedrich Nietzsche", quote: "There are various eyes.Even the Sphinx has eyes and as a result there are various truths, and as a result there is no truth." },
  { author: "Friedrich Nietzsche", quote: "One ought to hold on to one's heart; for if one lets it go, one soon loses control of the head too." },
  { author: "Franz Kafka", quote: "Evil is whatever distracts." },
  { author: "Franz Kafka", quote: "A first sign of the beginning of understanding is the wish to die." },
  { author: "Franz Kafka", quote: "My 'fear' is my substance, and probably the best part of me." },
  { author: "Franz Kafka", quote: "Don't despair, not even over the fact that you don't despair." },
]
const seedQuotes = () => Quote.bulkCreate(quoteData)

module.exports = seedQuotes
